### ISSUE TITLE
Planetary (scuttlego) not connecting to peers

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1166] opened 2023-02-17 16:18 UTC
My copy of Planetary has stopped connecting to peers after upgrading to scuttlego. I tried restarting the app but it didn't help. I'm running on a Mac, TestFlight build 399, logs attached.

[7B64E837-B53D-4710-A339-C41EECA2FD8B.zip](https://github.com/planetary-social/planetary-ios/files/10768717/7B64E837-B53D-4710-A339-C41EECA2FD8B.zip)

**Comment by mplorentz** [comment] 2023-02-17 16:20
I just saw 1 peer connected for a second in the Connected Peers list but it went away quickly and I didn't get any new posts.

**Comment by mplorentz** [comment] 2023-02-17 16:31
It looks like the same thing is happening on my iPhone now. Here are the logs: [AB0FDE0A-FA6D-4BCD-B7FF-FE491375A812.zip](https://github.com/planetary-social/planetary-ios/files/10768851/AB0FDE0A-FA6D-4BCD-B7FF-FE491375A812.zip)

**Comment by martindsq** [comment] 2023-02-22 18:39
@mplorentz I had a similar problem where scuttlego hardly retrieved a lot of feeds I was following. It's highly probable it is not the same problem as me, but, just in case, my installation never connected to the planetary system pubs, that led me to debug that part and I found that my AppConfiguration had "Joined Planetary Network" set to false, I set it to true manually in swift, I don't know what's the cause of it, maybe I never set it, or maybe I did unset it some time ago. Maybe you have the same problem? You can check that quickly in the debug menu:

![IMG_DD356D851669-1](https://user-images.githubusercontent.com/1703242/220725631-26df9609-76b3-4154-b40b-21743839b0a8.jpeg)

**Comment by mplorentz** [comment] 2023-02-22 21:52
@martindsq oh very interesting! Both my Mac and iPhone profiles have Joined Planetary Network = `false`. I expected at least my iPhone one to be `true`. However I'm not actually seeing this problem anymore on TestFlight build 404. Both my devices show pubs, rooms, and room peers in the sidebar. However my iPhone is not getting any new messages.

**Comment by boreq** [comment] 2023-02-23 12:48
Yeah looking at your logs I don't see this happening at all. In fact I can see that you have been connecting to peers :shrug:

**Comment by boreq** [comment] 2023-02-23 12:48
I am going to close this for now to limit noise.

**Closed by boreq** 2023-02-23 12:48 UTC
Labels: bug, 2.0
