### ISSUE TITLE
Planetary will not download your own feed

### ISSUE THREAD

**Issue by quickdudley** [planetary-social/planetary-ios#847] opened 2022-09-17 02:20 UTC
*To replicate*:
1. Reinstall planetary on an iOS device which has previously had it installed and go through the mandatory new account setup
2. In the advanced and dangerous settings: select the previous account

*Expected results*:
Planetary should redownload the original feed

*Actual results*:
Planetary followed the account @l/lzpaG3asUP+kSj1KNdEvh+oIzjmsPBk20X5er3YrI=.ed25519 and did not download any messages from the feed being restored.

**Comment by mplorentz** [comment] 2022-09-29 13:51
I was able to reproduce this today. 

As I explained on SSB, the Planetary Help auto-follow does not actually publish a message on your feed and fork it, although the UI does make it seem that way. I opened #873 to make this more obvious. 

The real issue the expected outcome is not happening is this: there is a bug in the EBT implementation of go-ssb. It won't redownload your own feed after a restore. If you connect to a peer that only supports legacy gossip then your feed will be restored correctly. I'm going to edit the title to reflect this. We are treating this as an EBF and will try to get a fix out ASAP.

**Comment by mplorentz** [comment] 2022-09-29 13:55
Another set of steps to reproduce look like this:
1. Set up a Planetary account with some published posts
2. Delete Planetary from the device
3. Reinstall Planetary
4. Open Planetary
Expected: your feed is redownloaded.
Actual: your feed is not downloaded.

One way to fix this is to find a peer that doesn't support EBT replication and connect to them manually. You can connect manually from the Debug menu by going to Go Bot -> paste a multi server address in the "Connect to Peer" box -> tap "Connect".

**Comment by mplorentz** [comment] 2022-09-29 20:39
I found a temporary fix for this issue today. If we disable EBT replication on our pubs, and fix another bug in go-ssb (#875) so that it correctly falls back to legacy gossip then it gets feed restoration working. Unfortunately this requires a deployment of the iOS app. I am aiming to release it on Monday.

I'm also not convinced that the EBT issue is even in go-ssb, it may be in the [ssb-ebt](https://github.com/ssbc/ssb-ebt) or epidemic-broadcast-trees](https://github.com/ssbc/epidemic-broadcast-trees) Node.js plugins that our pubs use. I wrote up some weird behavior I am seeing here: https://github.com/ssbc/ssb-ebt/issues/59.

**Comment by rabble** [comment] 2022-10-10 19:46
Let's reach out to @mixmix about helping fix this because it's a bug in the JS ebt libraries.

**Comment by mplorentz** [comment] 2022-10-13 18:05
Update: Mix and I are working on a test to reproduce this.

**Comment by rabble** [comment] 2022-10-24 19:57
@boreq and @mixmix will check in on this.

**Comment by rabble** [comment] 2022-11-07 20:41
@mixmix what's the status of this getting fixed in the JS stack

**Comment by mplorentz** [comment] 2022-12-05 21:11
The temporary fix I described in https://github.com/planetary-social/planetary-ios/issues/847#issuecomment-1262789919 was undone (because those pubs totally stopped working with no error messages 🤷‍♂️ ) so I have opened #985 as another workaround.

**Comment by martindsq** [comment] 2023-02-17 14:41
@mplorentz should we close this? scuttlego is definitely pulling the user's feed

**Comment by mplorentz** [comment] 2023-02-17 15:07
Yeah we can close this. Scuttlego is only pulling our own feed because Filip wrote some workaround code to use legacy gossip in that case. But it does fix the bug in Planetary. 

It would be nice to get rid of the workaround someday. I still think there is a bug in the javascript implementation of EBT, but I already spent over 40 hours trying to solve it myself, @mixmix spent many hours as well, and @andrestaltz says its fixed and closed [the issue](https://github.com/ssbc/ssb-ebt/issues/59) so I don't see what more can be done here on our end.

**Closed by mplorentz** 2023-02-17 15:07 UTC
Labels: bug
