### ISSUE TITLE
Update User Profile Display

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#680] opened 2022-06-30 01:49 UTC
When viewing a user's profile to see their posts, we should be able to see all the activity on their feed that we've got the ability to display.

- [ ] Display likes, follows, replies, and blocks on a user's profile for their feed
- [ ] Display a list of who the user has blocked
- [ ] Display a feed of content from the perspective of that user. 
- [ ] Display mutuals when listing following / followers / blocks

At the moment when you view a profile you only see the threads they started. We need a few things added. We should be able to see all of their activity, but also a tab which shows what this person sees. 

If the profile is a pub, then the default should be to display the feed from their perspective, who do they follow. If the profile is not a pub, then first we see everything they have posted, with the ability to switch to see what they follow.

This needs design, which is ticket: #681

**Comment by mplorentz** [comment] 2022-07-25 20:12
Duplicate of #681

**Closed by mplorentz** 2022-07-25 20:12 UTC
Labels: enhancement, help wanted, medium
