### ISSUE TITLE
Modern URI support

### ISSUE THREAD

**Issue by danlatorre** [planetary-social/planetary-ios#1063] opened 2022-12-22 22:04 UTC
Via @mixmix on SSB

Link : ssb:message/sha256/Uh6Qk_9ncyKFJWJXDOeLSU1CLIagXc-ANyT999Ol5dw= 
(this is the modern sort of uri planetary needs to support)

**Comment by rabble** [comment] 2022-12-22 22:51
Dupe of #382

**Closed by rabble** 2022-12-22 22:51 UTC
