### ISSUE TITLE
interaction bug - follow button appearing / disapearing

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#227] opened 2021-02-27 21:38 UTC
"When I tap into a profile (like on the hashtag tab), I can see a follow button. But if I go to another tab and back, the button disappears. The button under the … button on a post is still there."

**Comment by mplorentz** [comment] 2022-02-09 00:07
@rabble I'm not seeing this anymore. Can you confirm and close?

**Comment by setch-l** [comment] 2022-02-21 16:51
Closing - unable to reproduce.

**Closed by setch-l** 2022-02-21 16:51 UTC
Labels: bug
