### ISSUE TITLE
backup and restoring ssb keys in ios app

### ISSUE THREAD

**Issue by amandabee** [planetary-social/planetary-ios#285] opened 2022-01-20 16:54 UTC
See #251

Trying to use these instructions to migrate my key: https://github.com/planetary-social/planetary-ios/wiki/Backing-Up-Your-Key 

Couple of walls I've hit:

1) I only need the part in the squiggle brackets -- that includes the identity and they key. I thought I needed to back up both. Minor inconvenience.

2) We alternate between talking about "keys" and "identity and secret" which is eventually going to confuse people. Not worried about that right this second but we should be consistent.

3) Once I've added my "identity and secret" there's no apparent way to "save".  I select "Next" and get to a screen with my Configuration Name, onboarding status, statistics and identity, but I can't do anything there.  Going back (by selecting ` < Secret `) takes me to the initial debut screen where my identity is not stored. 

![Screenshot of Configuration Settings](https://user-images.githubusercontent.com/150791/150403007-28eb1aab-3f15-4909-abe1-166a98085414.jpg)

**Comment by mplorentz** [comment] 2022-06-27 19:39
Closing this as a duplicate of #251

**Closed** 2022-07-12 20:43 UTC
