### ISSUE TITLE
Context menu to add a photo as profile picture fails on iPad in landscape mode

### ISSUE THREAD

**Issue by kode54** [planetary-social/planetary-ios#339] opened 2022-02-03 07:08 UTC
Steps to reproduce:

1. Create Profile in landscape orientation
2. Attempt to add photo
3. Fails

It fails with something about failing to satisfy an auto layout constraint. Clearly the positioning layout for the context menu is not designed for use on landscape layout tablets.

**Comment by mplorentz** [comment] 2022-02-03 22:23
Closing as a duplicate of #231. Thanks for the report though, I copied the steps to reproduce to the new ticket because they were better than what we had.

**Closed by mplorentz** 2022-02-03 22:23 UTC
